version: '3'
services:
  app:
    hostname: app
    container_name: app
    restart: always
    build:
      context: ./
    ports:
      - "8080:8080"
    environment:
      - ADMIN_HASH=ZehL4zUy-3hMSBKWdfnv86aCsnFowOp0Syz1juAjN8U=
      - LOG_LEVEL=trace
    depends_on:
      - redis

  redis:
    hostname: redis
    container_name: redis
    image: redis:5.0-alpine
    volumes:
      - ./redis-data:/data
    # ports:
    #   - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
