// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api-v1-users/server.proto

package api_v1_users

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *AddRoleRequest) Validate() error {
	return nil
}
func (this *AuthRequest) Validate() error {
	return nil
}
func (this *AuthResponse) Validate() error {
	for _, item := range this.Errors {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Errors", err)
			}
		}
	}
	return nil
}
func (this *Error) Validate() error {
	return nil
}
func (this *CreateUserRequest) Validate() error {
	return nil
}
func (this *CreateUserResponse) Validate() error {
	return nil
}
