// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api-v1-users/server.proto

package api_v1_users

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResponseStateCode int32

const (
	ResponseStateCode_CREATED ResponseStateCode = 0
)

var ResponseStateCode_name = map[int32]string{
	0: "CREATED",
}

var ResponseStateCode_value = map[string]int32{
	"CREATED": 0,
}

func (x ResponseStateCode) String() string {
	return proto.EnumName(ResponseStateCode_name, int32(x))
}

func (ResponseStateCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fdd6cb6214e7ec5d, []int{0}
}

type AuthRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdd6cb6214e7ec5d, []int{0}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors               []*Error `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdd6cb6214e7ec5d, []int{1}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AuthResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *AuthResponse) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdd6cb6214e7ec5d, []int{2}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreateUserRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Company              string   `protobuf:"bytes,3,opt,name=company,proto3" json:"company,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdd6cb6214e7ec5d, []int{3}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserRequest) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

type CreateUserResponse struct {
	StateCode            ResponseStateCode `protobuf:"varint,1,opt,name=stateCode,proto3,enum=api.v1.users.ResponseStateCode" json:"stateCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdd6cb6214e7ec5d, []int{4}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetStateCode() ResponseStateCode {
	if m != nil {
		return m.StateCode
	}
	return ResponseStateCode_CREATED
}

func init() {
	proto.RegisterEnum("api.v1.users.ResponseStateCode", ResponseStateCode_name, ResponseStateCode_value)
	proto.RegisterType((*AuthRequest)(nil), "api.v1.users.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "api.v1.users.AuthResponse")
	proto.RegisterType((*Error)(nil), "api.v1.users.Error")
	proto.RegisterType((*CreateUserRequest)(nil), "api.v1.users.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "api.v1.users.CreateUserResponse")
}

func init() { proto.RegisterFile("api-v1-users/server.proto", fileDescriptor_fdd6cb6214e7ec5d) }

var fileDescriptor_fdd6cb6214e7ec5d = []byte{
	// 435 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x4d, 0xd3, 0x8f, 0x49, 0x55, 0xe8, 0x96, 0x83, 0xe3, 0x0b, 0x96, 0x4f, 0x55, 0x50,
	0x6c, 0x25, 0xdc, 0x2a, 0x55, 0x28, 0x0a, 0x39, 0x70, 0x43, 0x0e, 0x48, 0x88, 0x4b, 0x35, 0x75,
	0x46, 0xce, 0x42, 0xe2, 0x5d, 0x76, 0xd6, 0xae, 0x72, 0xe5, 0x2f, 0xf0, 0xd3, 0x38, 0xf0, 0x07,
	0xf8, 0x21, 0xc8, 0x5f, 0xd4, 0xa5, 0xf4, 0xc2, 0xc5, 0xda, 0x37, 0x6f, 0xf6, 0xbd, 0x79, 0xeb,
	0x81, 0x21, 0x6a, 0x39, 0x2e, 0x26, 0xe3, 0x9c, 0xc9, 0x70, 0xc4, 0x64, 0x0a, 0x32, 0xa1, 0x36,
	0xca, 0x2a, 0x71, 0x82, 0x5a, 0x86, 0xc5, 0x24, 0xac, 0x28, 0xef, 0x53, 0x2a, 0xed, 0x3a, 0xbf,
	0x09, 0x13, 0xb5, 0x8d, 0x52, 0xa3, 0x93, 0x31, 0x25, 0x8a, 0x77, 0x6c, 0xa9, 0x81, 0x29, 0x5a,
	0xba, 0xc5, 0x5d, 0x64, 0xd7, 0xd2, 0xac, 0xae, 0x35, 0x1a, 0xbb, 0x8b, 0x52, 0xa5, 0xd2, 0x0d,
	0xa1, 0x96, 0xdc, 0x1c, 0x23, 0xd4, 0x32, 0xc2, 0x2c, 0x53, 0x16, 0xad, 0x54, 0x19, 0xd7, 0x4e,
	0xc1, 0x6b, 0x18, 0xcc, 0x72, 0xbb, 0x8e, 0xe9, 0x6b, 0x4e, 0x6c, 0xc5, 0x73, 0xe8, 0xd3, 0x16,
	0xe5, 0xc6, 0x75, 0x7c, 0xe7, 0xe2, 0x38, 0xae, 0x81, 0xf0, 0xe0, 0x48, 0x23, 0xf3, 0xad, 0x32,
	0x2b, 0x77, 0xaf, 0x22, 0xfe, 0xe0, 0x20, 0x85, 0x93, 0x5a, 0x80, 0xb5, 0xca, 0x98, 0x4a, 0x05,
	0xab, 0xbe, 0x50, 0xd6, 0x2a, 0x54, 0xa0, 0xac, 0x16, 0xb8, 0x91, 0xf5, 0xf5, 0xa3, 0xb8, 0x06,
	0xe2, 0x25, 0x1c, 0x90, 0x31, 0xca, 0xb0, 0xdb, 0xf3, 0x7b, 0x17, 0x83, 0xe9, 0x79, 0xd8, 0xcd,
	0x1d, 0x2e, 0x4a, 0x2e, 0x6e, 0x5a, 0x82, 0x2b, 0xe8, 0x57, 0x05, 0x21, 0x60, 0x3f, 0x51, 0x2b,
	0xaa, 0x0c, 0xfa, 0x71, 0x75, 0x16, 0x3e, 0x0c, 0x56, 0xc4, 0x89, 0x91, 0xba, 0x0c, 0xd7, 0x0c,
	0xd9, 0x2d, 0x05, 0xd7, 0x70, 0x36, 0x37, 0x84, 0x96, 0x3e, 0x30, 0x99, 0xff, 0x8e, 0x2b, 0x5c,
	0x38, 0x4c, 0xd4, 0x56, 0x63, 0xb6, 0x73, 0x7b, 0x15, 0xd5, 0xc2, 0x60, 0x09, 0xa2, 0x6b, 0xd0,
	0x3c, 0xc7, 0x15, 0x1c, 0xb3, 0x45, 0x4b, 0xf3, 0x76, 0xe2, 0xd3, 0xe9, 0x8b, 0xfb, 0x29, 0xdb,
	0xd6, 0x65, 0xdb, 0x16, 0xdf, 0xdd, 0x18, 0xf9, 0x70, 0xf6, 0x80, 0x17, 0x03, 0x38, 0x9c, 0xc7,
	0x8b, 0xd9, 0xfb, 0xc5, 0x9b, 0x67, 0x4f, 0xa6, 0x3f, 0x1d, 0x78, 0x5a, 0x3a, 0xf2, 0xec, 0xdd,
	0xdb, 0x25, 0x99, 0x42, 0x26, 0x24, 0x3e, 0x03, 0xdc, 0x8d, 0x22, 0xfe, 0xf2, 0x7b, 0xf0, 0x0a,
	0x9e, 0xff, 0x78, 0x43, 0x6d, 0x1d, 0x0c, 0xbf, 0xfd, 0xf8, 0xf5, 0x7d, 0xef, 0x3c, 0x38, 0x8d,
	0x8a, 0x49, 0x54, 0xef, 0x6b, 0xf9, 0xbd, 0x74, 0x46, 0xe2, 0x23, 0xec, 0x97, 0xff, 0x5f, 0x0c,
	0xef, 0x8b, 0x74, 0x96, 0xca, 0xf3, 0xfe, 0x45, 0x3d, 0xae, 0x8c, 0xb9, 0x5d, 0x5f, 0x3a, 0xa3,
	0x9b, 0x83, 0x6a, 0x43, 0x5f, 0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xfc, 0x6f, 0x29, 0x2a, 0x28,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UsersAPIServiceClient is the client API for UsersAPIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsersAPIServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
}

type usersAPIServiceClient struct {
	cc *grpc.ClientConn
}

func NewUsersAPIServiceClient(cc *grpc.ClientConn) UsersAPIServiceClient {
	return &usersAPIServiceClient{cc}
}

func (c *usersAPIServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/api.v1.users.UsersAPIService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersAPIServiceClient) Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/api.v1.users.UsersAPIService/Auth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersAPIServiceServer is the server API for UsersAPIService service.
type UsersAPIServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	Auth(context.Context, *AuthRequest) (*AuthResponse, error)
}

// UnimplementedUsersAPIServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUsersAPIServiceServer struct {
}

func (*UnimplementedUsersAPIServiceServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedUsersAPIServiceServer) Auth(ctx context.Context, req *AuthRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Auth not implemented")
}

func RegisterUsersAPIServiceServer(s *grpc.Server, srv UsersAPIServiceServer) {
	s.RegisterService(&_UsersAPIService_serviceDesc, srv)
}

func _UsersAPIService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersAPIServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.users.UsersAPIService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersAPIServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersAPIService_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersAPIServiceServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.users.UsersAPIService/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersAPIServiceServer).Auth(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UsersAPIService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.users.UsersAPIService",
	HandlerType: (*UsersAPIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UsersAPIService_CreateUser_Handler,
		},
		{
			MethodName: "Auth",
			Handler:    _UsersAPIService_Auth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api-v1-users/server.proto",
}
